### ISSUE TITLE
keep items in list when 0

### ISSUE THREAD

**Issue by rubo77** [Abrynos/ShoppingList#106]
### Checklist

- [X] I read and understood the **[Contributing Guidelines](https://github.com/Abrynos/ShoppingList/blob/main/.github/CONTRIBUTING.md)**.
- [X] This is not a **[question](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[technical issue](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[duplicate](https://github.com/Abrynos/ShoppingList/issues)** of an existing issue.
- [X] This idea is not already possible.
- [X] I believe my idea falls into the projects scope and should be offered as part of the built-in functionality.

### Purpose

Enhancement

### Solution

If you click on a item that you have already in your basket, it should Stay in the list unless you press the delete button

### Why are the currently available solutions not sufficient?

Not aplicable

### Can you help us with this feature request?

No, I don't have time, skills or willings for any of that.

**Comment by Abrynos** [comment]
Interesting idea. Feel free to add this in a PR. But please make sure it's behind a new setting.

**Comment by rubo77** [comment]
did you close this on purpose? or is there a follow-up PR or a commit, where it is solved?

**Comment by Abrynos** [comment]
> did you close this on purpose? or is there a follow-up PR or a commit, where it is solved?

I closed it on purpose and added the "merge request ok" label to indicate I'll be happy to accept a merge request, but I don't like to have a bunch of issues open that I don't see being worked on anytime soon.

I personally don't plan on implementing this and you chose the option of "No, I don't have time, skills or willings for any of that". Therefore, there is no indication of this feature being added soon.

If you do plan on working on this, feel free to re-open the issue with a corresponding comment.
