### ISSUE TITLE
Language request: add Azerbaijani, Georgian and Turkish languages to Crowdin

### ISSUE THREAD

**Issue by DraganRatkovich** [Abrynos/ShoppingList#119]
### Checklist

- [X] I read and understood the **[Contributing Guidelines](https://github.com/Abrynos/ShoppingList/blob/main/.github/CONTRIBUTING.md)**.
- [X] This is not a **[question](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[technical issue](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[duplicate](https://github.com/Abrynos/ShoppingList/issues)** of an existing issue.
- [X] This idea is not already possible.
- [X] I believe my idea falls into the projects scope and should be offered as part of the built-in functionality.

### Purpose

Azerbaijani, Georgian and Turkish languages are currently not available for the application, so I decided to take advantage of this golden opportunity and translate into these three languages.

### Solution

@Abrynos Add all three languages to Crowdin so I can start translating the application into the specified languages. Also, if your projects use an approval system, appoint me as a proofreader for three languages.

### Why are the currently available solutions not sufficient?

Currently, as described above, these three languages are not available.

### Can you help us with this feature request?

Yes, I can code the solution myself and send a merge request.

### Additional information

Sorry if this issue is open under the wrong label, in which case please move it or let me know somewhere else to open a request to add a language.

**Comment by DraganRatkovich** [comment]
@Abrynos Sorry, I forgot to mention, my Crowdin username is DraganRatkovich. I joined the project a few minutes ago.

**Comment by Abrynos** [comment]
If I may ask: How come you speak this many (in part quite similar from what I hear) languages?

I've added them to crowdin. Happy translating and thanks for your contribution!

**Comment by DraganRatkovich** [comment]
@Abrynos Hello,

I am Azerbaijani by nationality, a citizen of Georgia, and therefore Georgian is my second native language after Azerbaijani. As for Turkish, it is very similar to Azerbaijani, with minor differences in grammar, etc.

**Comment by DraganRatkovich** [comment]
@Abrynos Hi,

The translation into three languages is ready, but you forgot to appoint me as a proofreader for them so that I could approve my translations.

**Comment by Abrynos** [comment]
@DraganRatkovich Sorry for the late answer. I just got back home. The changes were merged in #120 and I'll create a release soon.

Thank you for your contribution! 🥇
