### ISSUE TITLE
Share item

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [Abrynos/ShoppingList#12]
Currently, only the article that is being entered can be shared. 
Items already on the shopping list cannot be shared.

Suggestion: Every single item on the shopping list can be shared with someone.
(And this someone can then click on the link and add it to the shopping list).

**Comment by Abrynos** [comment]
I am thinking, that sharing the whole list might be a bit too restrictive. Maybe I just want to send the most important five items on my list and get the other ones myself when I have time. I'll look into sharing more than one item.

**Comment by mondlicht-und-sterne** [comment]
why do you label all the issues when you are more or less against it with the other issue and with this issue? then with a third issue there is surely a no again. oh well.

**Comment by Abrynos** [comment]
I label them as what they are. And how do you figure I am against this feature request? I actually like it and I intend to implement it.

**Comment by Abrynos** [comment]
Will close for now with the merge request okay label. Until now the situation where this was necessary never occured to me, but I see the potential. If anyone wants to implement it: I'm willing to merge it at any point in time.
