### ISSUE TITLE
confirm delete

### ISSUE THREAD

**Issue by pescepalla** [Abrynos/ShoppingList#123]
### Checklist

- [X] I read and understood the **[Contributing Guidelines](https://github.com/Abrynos/ShoppingList/blob/main/.github/CONTRIBUTING.md)**.
- [X] This is not a **[question](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[technical issue](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[duplicate](https://github.com/Abrynos/ShoppingList/issues)** of an existing issue.
- [X] This idea is not already possible.
- [X] I believe my idea falls into the projects scope and should be offered as part of the built-in functionality.

### Purpose

People with fat fingers easily hit the delete (trashcan) button instead of the minus button. Currently the app allows loss of data without confirmation (and possibly without the user realizing).

### Solution

There might be an option that makes the app require confirmation after hitting the delete button.

### Why are the currently available solutions not sufficient?

Any item on the list is one tap away from deletion. A wrong tap can cause annoyance (if the tap is detected) or worse if the tap is undetected.

### Can you help us with this feature request?

Somehow, I can test and offer feedback, but I can't code the solution.

**Comment by Abrynos** [comment]
Thank you for your suggestion. This sounds like a nice feature to add at some point with a simple boolean switch in the settings and an `AlertDialog`. I feel this could be a really nice merge request for someone willing to contribute to the project.
