### ISSUE TITLE
Adding a backend

### ISSUE THREAD

**Issue by Darkfrobozz** [Abrynos/ShoppingList#126]
### Checklist

- [X] I read and understood the **[Contributing Guidelines](https://github.com/Abrynos/ShoppingList/blob/main/.github/CONTRIBUTING.md)**.
- [X] This is not a **[question](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[technical issue](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[duplicate](https://github.com/Abrynos/ShoppingList/issues)** of an existing issue.
- [X] This idea is not already possible.
- [X] I believe my idea falls into the projects scope and should be offered as part of the built-in functionality.

### Purpose

Currently, one of the biggest advantages of an online shopping list is to be able to share it with the family and have it consistently update.

### Solution

I would be willing to sponsor the hosting of a REST API backend. Also, help with it's development. However, I have no knowledge of kotlin and cannot help in this manner.

Primarily, I think a simple database that stores related to a key generated by the user can be used. This way family can share the same key and make requests. This means we can avoid integration with mails and other unnecessary baggage.

A part of the solution will be necessarily not part of this repo as it is a different process.

### Why are the currently available solutions not sufficient?

It does not provide a family integration

### Can you help us with this feature request?

Somehow, I can test and offer feedback, but I can't code the solution.

**Comment by Abrynos** [comment]
Hi :) Thanks for your interest in further development of the app!

As per my comment on #63. I'd be happy to implement it, but since I live alone (and my life isn't as eventless as I'd like it to be), I currently have neither the need nor motivation or time to work on this myself.

**Comment by Darkfrobozz** [comment]
Alternatively, perhaps the cloud sync could be used for this. Then, maybe a little about that in the README could guide users on setting it up. This could be a much easier solution work-wise.

**Comment by Abrynos** [comment]
> perhaps the cloud sync could be used for this

Could you expand on what exactly you mean by that?

**Comment by Darkfrobozz** [comment]
> > perhaps the cloud sync could be used for this
> 
> Could you expand on what exactly you mean by that?

There was a previous issue about providing a location where the files are stored, is there a straightforward way to set the file storage to a cloud storage location?

If so, a guide to that could be used instead of a backend.

**Comment by Abrynos** [comment]
There currently is no way to configure a file-location since the list is stored in an SQLite database called [room](https://developer.android.com/jetpack/androidx/releases/room). Such thing would also require a merge request, but I'd much rather prefer a solution with an actual backend.

**Comment by Darkfrobozz** [comment]
Alright gotcha, thanks for the quick response!
