### ISSUE TITLE
Copy list to lock screen

### ISSUE THREAD

**Issue by sengels** [Abrynos/ShoppingList#128]
### Checklist

- [X] I read and understood the **[Contributing Guidelines](https://github.com/Abrynos/ShoppingList/blob/main/.github/CONTRIBUTING.md)**.
- [X] This is not a **[question](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[technical issue](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[duplicate](https://github.com/Abrynos/ShoppingList/issues)** of an existing issue.
- [X] This idea is not already possible.
- [X] I believe my idea falls into the projects scope and should be offered as part of the built-in functionality.

### Purpose

My issue:
When I go shopping, I always need to unlock my phone to read the shoppingList. It would be nice to have the shoppingList as notifications instead.

### Solution

My idea is to use notifications (just like the "new chat message" notification) which are displayed on the welcome screen.
When you found the item, you should be able to swipe away that notification. Ideally that would also change the status of the item on your list.

### Why are the currently available solutions not sufficient?

...

### Can you help us with this feature request?

Yes, I can code the solution myself and send a merge request.

### Additional information

Possible restrictions I can see for this feature:
- Notifications on the lock screen are not everybody's choice, So this might not work easily everywhere.
- The interaction with the app might not make it possible to "mark items as bought", e.g. even if you click away the notification it would still be open. I wouldn't mind this part though.
- Items might get grouped together so that you can't see each individual item anymore. Depending on the implementation, there might be ways to circumvent this, especially if you have a way to "mark items as bought" (you could then always show the next item)
p.s.: Thanks for the app!

**Comment by Abrynos** [comment]
> My idea is to use notifications (just like the "new chat message" notification) which are displayed on the welcome screen. When you found the item, you should be able to swipe away that notification.

This sounds cumbersome/unwieldy. For me it would make much more sense to use the full lockscreen like google maps already does (assuming the app is in the foreground when initially locking the screen).

Anyways: I like the idea. Let me know if you plan on sending a merge request.

**Comment by Abrynos** [comment]
Closing as currently not planned; Maybe someone else wants to implement it.
