### ISSUE TITLE
Create shopping lists

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [Abrynos/ShoppingList#13]
My idea was that items can be added to shopping lists or copied or moved to them. Example: Buy 3 apples at Penny and 5 apples at Lidl.
And that you can also edit and delete the shopping list you have created.
The idea would be to share the respective shopping list with someone else, 
i.e. not just 1 apple but the following from Penny.

**Comment by Abrynos** [comment]
I see this as out of scope. I want to keep the whole thing as simple as possible and I wouldn't start a piece of paper for every shop I go to. When you go shopping more often you usually know, that you don't want the minced meat from Billa, but from your local butcher.

**Comment by mondlicht-und-sterne** [comment]
then we can also close the issue

**Comment by Abrynos** [comment]
> then we can also close the issue

correct. I was hung up with labels 😄 Thanks for reminding me
