### ISSUE TITLE
Add Bangla Language Support

### ISSUE THREAD

**Issue by asem-hamid** [Abrynos/ShoppingList#131]
There is no Bangla Language Support in app

I can manually add translation of Bangla , if it assign to me

**Comment by Abrynos** [comment]
You know... Issue templates are usually there for a reason and everyone else has managed to fill them out.

Anyways: I've added Bengali in crowdin. It can be translated [here](https://crowdin.com/project/abrynosshoppinglist/bn).

**Comment by asem-hamid** [comment]
Can i do it manually by adding values-bn/string.yml
