### ISSUE TITLE
Add Finnish translation

### ISSUE THREAD

**Issue by minna-xD** [Abrynos/ShoppingList#22]
### Checklist

- [X] I read and understood the **[Contributing Guidelines](https://github.com/Abrynos/ShoppingList/blob/main/.github/CONTRIBUTING.md)**.
- [X] This is not a **[question](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[technical issue](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[duplicate](https://github.com/Abrynos/ShoppingList/issues)** of an existing issue.
- [X] This idea is not already possible.
- [X] I believe my idea falls into the projects scope and should be offered as part of the built-in functionality.

### Purpose

Adding Finnish translation for the app would allow Finnish people to use it more easily

### Solution

I am able to add the translation

### Why are the currently avialable solutions not sufficient?

Finnish is currently missing

### Can you help us with this feature request?

Yes, I can code the solution myself and send a merge request.

### Additional information

This is the first time I come across a template like this, I hope I did ok!
Happy Hacktoberfest! I was browsing topics under translation for a soft start of the season and this project seemed like a nice one to start with if you are participating this year.

**Comment by Abrynos** [comment]
Hello there :)

First I want to thank you for opening this issue. I like the idea of supporting languages for more people to enjoy the project, but I fear there is little to no coding required for adding a new language. I have just added Finnish over on [crowdin](https://crowdin.com/project/abrynosshoppinglist) for translation. When someone finds time to do this, the strings will automatically be merged to GitHub.

In case Finnish capitalizes nouns (a short google search said "yes" for me), there is some change to be implemented in terms of code: Set the flag for capitalization in [AddItemActivity.kt](https://github.com/Abrynos/ShoppingList/blob/main/app/src/main/java/pl/edu/pjwstk/s999844/shoppinglist/AddItemActivity.kt#L66). You can do this by simply adding another case to the when expression that already does this for German.

You did perfect! Happy Hacktoberfest to you too!

**Comment by minna-xD** [comment]
Hi!

Finnish doesn't actually capitalize nouns so no need to set a flag.

For Hacktoberfest I would need to do a pull request which was mentioned as a possibility in the readme. Are you fine with me creating a values-fi folder inside app/src/main/res/ containing the strings.xml?

**Comment by Abrynos** [comment]
Sure! Go ahead.

**Comment by Abrynos** [comment]
A first version containing finnish translations can be downloaded from our CI pipeline [over here](https://github.com/Abrynos/ShoppingList/actions/runs/1299068718)

**Comment by minna-xD** [comment]
Cool 👍🏻
