### ISSUE TITLE
Add Norwegian Bokmål translation

### ISSUE THREAD

**Issue by JarlavGrenland** [Abrynos/ShoppingList#33]
### Checklist

- [X] I read and understood the **[Contributing Guidelines](https://github.com/Abrynos/ShoppingList/blob/main/.github/CONTRIBUTING.md)**.
- [X] This is not a **[question](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[technical issue](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[duplicate](https://github.com/Abrynos/ShoppingList/issues)** of an existing issue.
- [X] This idea is not already possible.
- [X] I believe my idea falls into the projects scope and should be offered as part of the built-in functionality.

### Purpose

Adding Norwegian bokmål will let the majority of Norwegians use their preffered language

### Solution

I am able to translate the app in to Norwegian via CrowdIn

### Why are the currently avialable solutions not sufficient?

Norwegian Bokmål is currently missing

### Can you help us with this feature request?

Somehow, I can test and offer feedback, but I can't code the solution.

**Comment by Abrynos** [comment]
I've added Norwegian Bokmal in crowdin. You can find it over [here](https://crowdin.com/project/abrynosshoppinglist/nb). Thank you in advance for your contribution.
