### ISSUE TITLE
long item names overlapping with number of items

### ISSUE THREAD

**Issue by paulle** [Abrynos/ShoppingList#37]
### Checklist

- [X] I read and understood the **[Contributing Guidelines](https://github.com/Abrynos/ShoppingList/blob/main/.github/CONTRIBUTING.md)**.
- [X] This is not a **[question](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[technical issue](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[duplicate](https://github.com/Abrynos/ShoppingList/issues)** of an existing issue.

### Version

Latest stable release

### Description

Long item names overlapping with number of items

### Expected behaviour

Not overlapping

### Current behaviour

Long item names overlapping with number of items

### Steps to reproduce

Long item name with a number

### Can you help us with this bug report?

Somehow, I can test and offer feedback, but I can't code the solution.

### Additional information

Xperia 5, android 11
![Screenshot_20220102-160322](https://user-images.githubusercontent.com/4852079/147879933-b8751e5f-2911-4b8c-a479-e3d0ca08c67f.png)

**Comment by Abrynos** [comment]
That is a bummer. I thought to have already fixed it before, but apparently that fix only applies to my device. Thank you for reporting this.

**Comment by Abrynos** [comment]
Are you sure you're using the latest version? You can check it by looking at the text on the bottom of the settings menu. The currently latest version is `1.9.0`. 

I ask this, because I've just created an Android Emulator using the specs of the Xperia 5 (6.1 inch display, 1080x2520 pixels, 6GB memory, Android 11) and it seems to be working for me. 
![image](https://user-images.githubusercontent.com/6608231/147924920-088eb624-fe9d-4560-a176-9a74a3a2dc71.png)

**Comment by paulle** [comment]
Yes I'm using v 1.9.0

**Comment by Abrynos** [comment]
I've fixed the issue in a more dynamic way. Could you please test the `.apk` available from our CI pipeline [here](https://github.com/Abrynos/ShoppingList/actions/runs/1657846655)?

**Comment by paulle** [comment]
I don't see .apk for download.
Excuse me, maybe I'm blind or silly.

**Comment by Abrynos** [comment]
The linked page has a file named `artifacts.zip` at the bottom with the `.apk` inside it, as GitHub Actions does not allow direct upload of certain filetypes.

**Comment by paulle** [comment]
Nice, no more overlapping.

Thank you.

See attached screenshot.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------

**Comment by paulle** [comment]
![Screenshot_20220105-120540](https://user-images.githubusercontent.com/4852079/148208648-1890524f-b059-4938-8d6f-eceee39bbfdf.png)

**Comment by Abrynos** [comment]
Thank you very much. A new release should be available within a week or so.
