### ISSUE TITLE
sorting items in alphabetical order

### ISSUE THREAD

**Issue by paulle** [Abrynos/ShoppingList#38]
### Checklist

- [X] I read and understood the **[Contributing Guidelines](https://github.com/Abrynos/ShoppingList/blob/main/.github/CONTRIBUTING.md)**.
- [X] This is not a **[question](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[technical issue](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[duplicate](https://github.com/Abrynos/ShoppingList/issues)** of an existing issue.
- [X] This idea is not already possible.
- [X] I believe my idea falls into the projects scope and should be offered as part of the built-in functionality.

### Purpose

Sorting is nice to have in a longer list

### Solution

Sorting function

### Why are the currently avialable solutions not sufficient?

No sorting available

### Can you help us with this feature request?

Somehow, I can test and offer feedback, but I can't code the solution.

**Comment by Abrynos** [comment]
I've just implemented this. A first version is already available via our CI pipeline over [here](https://github.com/Abrynos/ShoppingList/actions/runs/1653482276). I'll wait a bit with the release to give our translators some time.
