### ISSUE TITLE
OLED/Pure Black dark mode

### ISSUE THREAD

**Issue by LianBg** [Abrynos/ShoppingList#39]
Due to the shitty Github issue forms, I had to rewrite this suggestion in an edit.

Simply: add an optional pure black dark mode to the app for OLED screen support.

**Comment by Abrynos** [comment]
Hey there!

Thank you for contacting our development team at GitHub.

**If you can't be bothered to fill out a simple form to properly present your idea, I cannot be bothered to read your suggestion.**


Have a nice day!
~Abrynos

**Comment by LianBg** [comment]
If you lack the mental capability to read a sentence without flashy lights and markdown around it, I didn't expect you to be able to change a single color code around either.

**Comment by Abrynos** [comment]
This is not about being mentally unable to comprehend the meaning of your sentence. **You want me to do something for you.** When you want something from me, I expect you to convince me to do it and not tell me to "simply do X". I am neither your employee nor your slave. 

On the other hand if you open merge request implementing the idea you don't have to argue much on the "why should this be included". I have to argue on the "why not" and that's much harder.
