### ISSUE TITLE
Units in the quantity section

### ISSUE THREAD

**Issue by shoalcreek5** [Abrynos/ShoppingList#42]
### Checklist

- [X] I read and understood the **[Contributing Guidelines](https://github.com/Abrynos/ShoppingList/blob/main/.github/CONTRIBUTING.md)**.
- [X] This is not a **[question](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[technical issue](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[duplicate](https://github.com/Abrynos/ShoppingList/issues)** of an existing issue.
- [X] This idea is not already possible.
- [X] I believe my idea falls into the projects scope and should be offered as part of the built-in functionality.

### Purpose

On the shopping list, sometimes quantities need to be weight-based units. For example, sugar and produce are often sold by weight and a unit would clarify. If I enter 5 for apples, do I need 5 kg of apples or do I need 5 apples? Currently, the app only allows the number pad with no way of entering units.

### Solution

Allow the full keyboard while entering quantities. Additionally, of not currently allowed, allow alphabetic text in the quantity field for an item.

### Why are the currently avialable solutions not sufficient?

As explained above, without the type of quantity, it is sometimes impossible to tell how much to buy. I can use another note taking app instead. That's often just as easy, I suppose.

### Can you help us with this feature request?

No, I don't have time, skills or willings for any of that.

**Comment by Abrynos** [comment]
Generally the idea of units is interesting, but implementing it would severely decrease the quality of user workflow. Changing the default keyboard from numbers to normal text, means every time a user wants to input the amount, they have to manually press at least one key on their keyboard to be able to tap the numbers.

I understand that sometimes you want to specify whether you need 5 apples of 5 kilogramms of apples, but usually (at least for me) no thinking whatsoever is required to remember which unit I need of an item, as soon as I see, that it is on my shopping list.
