### ISSUE TITLE
cross out

### ISSUE THREAD

**Issue by paulle** [Abrynos/ShoppingList#44]
### Checklist

- [X] I read and understood the **[Contributing Guidelines](https://github.com/Abrynos/ShoppingList/blob/main/.github/CONTRIBUTING.md)**.
- [X] This is not a **[question](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[technical issue](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[duplicate](https://github.com/Abrynos/ShoppingList/issues)** of an existing issue.
- [X] This idea is not already possible.
- [X] I believe my idea falls into the projects scope and should be offered as part of the built-in functionality.

### Purpose

Cross out item

### Solution

Another option, long press on a item will give the possibility to cross it out.

### Why are the currently available solutions not sufficient?

Till now not possible

### Can you help us with this feature request?

Somehow, I can test and offer feedback, but I can't code the solution.

**Comment by Abrynos** [comment]
This sounds like a nice solution to the feature request at hand. However, I personally am not really invested into this one, but I'm willing to accept it as part of merge request at any point.
