### ISSUE TITLE
Accent Color Setting

### ISSUE THREAD

**Issue by hl2guide** [Abrynos/ShoppingList#48]
### Checklist

- [X] I read and understood the **[Contributing Guidelines](https://github.com/Abrynos/ShoppingList/blob/main/.github/CONTRIBUTING.md)**.
- [X] This is not a **[question](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[technical issue](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[duplicate](https://github.com/Abrynos/ShoppingList/issues)** of an existing issue.
- [X] This idea is not already possible.
- [X] I believe my idea falls into the projects scope and should be offered as part of the built-in functionality.

### Purpose

Ability to set the accent color, currently only blue.

### Solution

Ability to set the accent color, currently only blue.

### Why are the currently available solutions not sufficient?

Only one accent color available, blue.

### Can you help us with this feature request?

No, I don't have time, skills or willings for any of that.

**Comment by Abrynos** [comment]
I've implemented this in a merge request, since it's quite a big change. I will wait a few day before merging to allow people to test the changes (which you are not willing to do for some reason).
