### ISSUE TITLE
marking things done in the list without deleting

### ISSUE THREAD

**Issue by paulle** [Abrynos/ShoppingList#51]
### Checklist

- [X] I read and understood the **[Contributing Guidelines](https://github.com/Abrynos/ShoppingList/blob/main/.github/CONTRIBUTING.md)**.
- [X] This is not a **[question](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[technical issue](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[duplicate](https://github.com/Abrynos/ShoppingList/issues)** of an existing issue.
- [X] This idea is not already possible.
- [X] I believe my idea falls into the projects scope and should be offered as part of the built-in functionality.

### Purpose

Marking things done

### Solution

An option with a long press on trash can, changing its color without deleting. So things done would be maked, without deleting it.

### Why are the currently available solutions not sufficient?

A possibility for that just now doesn't exist.

### Can you help us with this feature request?

Somehow, I can test and offer feedback, but I can't code the solution.

### Additional information

Nothing for now

**Comment by Abrynos** [comment]
As per my previous comment in #44 :

> I personally am not really invested into this one [feature], but I'm willing to accept it as part of merge request at any point.
