### ISSUE TITLE
Import/Export function

### ISSUE THREAD

**Issue by jberri** [Abrynos/ShoppingList#53]
### Checklist

- [X] I read and understood the **[Contributing Guidelines](https://github.com/Abrynos/ShoppingList/blob/main/.github/CONTRIBUTING.md)**.
- [X] This is not a **[question](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[technical issue](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[duplicate](https://github.com/Abrynos/ShoppingList/issues)** of an existing issue.
- [X] This idea is not already possible.
- [X] I believe my idea falls into the projects scope and should be offered as part of the built-in functionality.

### Purpose

There is no way to leverage the time I have invested in using ShoppingList by bringing over my lists to a new device. 

### Solution

An import/export function.

### Why are the currently available solutions not sufficient?

Doesn't exist.

### Can you help us with this feature request?

Somehow, I can test and offer feedback, but I can't code the solution.

**Comment by Abrynos** [comment]
This very much sounds like #12 .
