### ISSUE TITLE
replacing the +/- signs by the option marking an item as done

### ISSUE THREAD

**Issue by paulle** [Abrynos/ShoppingList#55]
### Checklist

- [X] I read and understood the **[Contributing Guidelines](https://github.com/Abrynos/ShoppingList/blob/main/.github/CONTRIBUTING.md)**.
- [X] This is not a **[question](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[technical issue](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[duplicate](https://github.com/Abrynos/ShoppingList/issues)** of an existing issue.
- [X] This idea is not already possible.
- [X] I believe my idea falls into the projects scope and should be offered as part of the built-in functionality.

### Purpose

replacing the +/- signs by the option marking an item as done.
I like your app very much, but I missed one feature, marking ab item as done without deleting it from the list and I never used the +/-  option. Because I put in the list the quantity 
3 lemons
2 kg potatos
Or simply
Milk
Bread
And so on

### Solution

Replace +/- by an option to mark items as done.
I don't know the behaviour of other users, may be they will like this change.

### Why are the currently available solutions not sufficient?

Because not available for now

### Can you help us with this feature request?

Somehow, I can test and offer feedback, but I can't code the solution.

**Comment by Abrynos** [comment]
I think this would be an interesting way of implementing the ideas of #44 , #51 and #40 .

Personally if anyone wants to implement this, I would like it to be an option in the settings to choose from.
