### ISSUE TITLE
Cloud Sync

### ISSUE THREAD

**Issue by jsmue** [Abrynos/ShoppingList#65]
### Checklist

- [X] I read and understood the **[Contributing Guidelines](https://github.com/Abrynos/ShoppingList/blob/main/.github/CONTRIBUTING.md)**.
- [X] This is not a **[question](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[technical issue](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[duplicate](https://github.com/Abrynos/ShoppingList/issues)** of an existing issue.
- [X] This idea is not already possible.
- [X] I believe my idea falls into the projects scope and should be offered as part of the built-in functionality.

### Purpose

I am looking for a minimalistic shopping list - in order to share its contents with the other people in my household.

### Solution

The app should at least allow to safe the data in a custom folder. This enables the user to sync a shopping list between devices.

### Why are the currently available solutions not sufficient?

There is no option given to safe files in a custom dir.

### Can you help us with this feature request?

Somehow, I can test and offer feedback, but I can't code the solution.

### Additional information

/

**Comment by Abrynos** [comment]
Feel free to send a merge request.
