### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [Abrynos/ShoppingList#7]
You can add Screenshots for F-Droid, too, if you want.
https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/
https://gitlab.com/snippets/1895688
That was simply information about what is still possible. You would then only have to enter the
screenshots in fastlane. This is just one way that you can also add screenshots to the app view
if you can. If you added screenshots (then F-Droid is happy) and if you can't add any -> then
you can close the issue because it was only an info. Thank you that your app is available in
fdroid. Very much for your attention.

**Comment by IzzySoft** [comment]
@Abrynos could you please add a line break before the languages bullet-point list in `full_description.txt` (same way as it is with "core features"), so it renders fine as Markdown again? Thanks! (And apologies for abusing this issue for it, but you have no "simple issue template" left for a "simple request" as this one 🙈)

**Comment by Abrynos** [comment]
Sure thing @IzzySoft 

For future reference, I believe the [discussion](https://github.com/Abrynos/ShoppingList/discussions) section might be fitting for such requests.

**Comment by IzzySoft** [comment]
Thanks – and good point!

Btw: ShoppingList is [back on IzzyOnDroid](https://apt.izzysoft.de/packages/pl.edu.pjwstk.s999844.shoppinglist), so if you want to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there you're welcome (and yes, we also have instructions for "shields" 😉). And congrats, your app is RB (see e.g. [Reproducible Builds, special client support and more at IzzyOnDroid](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients) for some background on this), so the green shield is up 🥳

**Comment by Abrynos** [comment]
> And congrats, your app is RB

Indeed, I've invested some time in the past (quite some time ago actually) to support this. It's also visible on [verification.f-droid.org/...](https://verification.f-droid.org/pl.edu.pjwstk.s999844.shoppinglist.json) 😄

**Comment by Abrynos** [comment]
> That only confirms that F-Droid can reproduce their own builds

Ah I didn't know that. Interesting. One would assume (since they obviously already run the infrastructure for checking multiple builds against each other), they'd use it for external verification.

**Comment by IzzySoft** [comment]
[Verifikationsserver](https://f-droid.org/docs/Verification_Server/) is not really clear about that. But the intro at https://verification.f-droid.org/ is:

> This is the [Verification Server](https://f-droid.org/wiki/page/Verification_Server) for https://f-droid.org/. It rebuilds apps from source that were built by f-droid.org and checks that the results match.

Going by the description, they also just check that the signature test succeeds. For our builds, we compare the checksums (sha256) of the files to ensure they are binary identical.
