### ISSUE TITLE
Allow to create lists for different events & allow editing on name, amount and etc.

### ISSUE THREAD

**Issue by LiamTheBox** [Abrynos/ShoppingList#75]
### Checklist

- [X] I read and understood the **[Contributing Guidelines](https://github.com/Abrynos/ShoppingList/blob/main/.github/CONTRIBUTING.md)**.
- [X] This is not a **[question](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[technical issue](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[duplicate](https://github.com/Abrynos/ShoppingList/issues)** of an existing issue.
- [X] This idea is not already possible.
- [X] I believe my idea falls into the projects scope and should be offered as part of the built-in functionality.

### Purpose

It can become a better tool when it has more features and is more customisable.

### Solution

Lists can be seen by sliding on the left or right (Right preferred)

Items can be edited by tapping on the pencil icon. Allow edit of name & amount.

Instead of a bin icon, change it to a check icon and make the text strike through, remove decoration by tapping the check icon again.

### Why are the currently available solutions not sufficient?

Making items dissapear and then realise it was the wrong item can be inconvenient.

The current add and subtract buttons use too much space for a smartphone.

### Can you help us with this feature request?

Somehow, I can test and offer feedback, but I can't code the solution.

### Additional information

You can contact me on Twitter, if you want me to draw sketches of your app and feature request.

**Comment by Abrynos** [comment]
> [x] This is not a [duplicate](https://github.com/Abrynos/ShoppingList/issues) of an existing issue.

As per issues #40, #44, #51 and #55:
- Merge requests are welcome for the features "cross-out" and "edit items"
- Multi-list support is out of scope as of now.
